apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: java-deployment
        image: shk2123/tenant:1.0.0
        ports:
        - containerPort: 8081
